service:
  name: epcal-exporter

plugins:
  - serverless-webpack
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 512
  timeout: 30
  apiKeys:
    - http_test

custom:
  s3:
    host: localhost
    port: 3214
    directory: .s3

resources:
  Resources:
    EpisodeCalendarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: epcal

functions:
  export:
    handler: src/index.handler
    events:
      - http:
          method: get
          cors: true
          private: true
    environment:
      EPISODECALENDAR_EMAIL: ${ssm:episodecalendarEmail}
      EPISODECALENDAR_PASSWORD: ${ssm:episodecalendarPassword}
