apiVersion: v1
kind: Secret
metadata:
  name: epcal-secret
type: Opaque
data:
  username: bm9uZQ==
  password: b2YgeW91ciBmdWNraW5nIGJ1c2luZXNz
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: epcal-export
  labels:
    app: epcal-export
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: epcal-export
          name: epcal-export
        spec:
          containers:
            - image: asnapper/epcal:1.0.0
              resources:
                limits:
                  cpu: 1
                  memory: 512Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              imagePullPolicy: Always
              name: epcal-export-job
              env:
                - name: EPCAL_PASS_PLAIN
                  valueFrom:
                    secretKeyRef:
                      name: epcal-secret
                      key: password
                - name: EPCAL_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: epcal-secret
                      key: username
                - name: DEBUG
                  value: "epcal:*"
                - name: EPCAL_OUT_DIR
                  value: /data
          restartPolicy: OnFailure